mengyunzhi/sign-in-through-code-scanning

- thinkphp/application/index/controller/StudentController.php
- thinkphp/application/index/view/Student/index.html
- thinkphp/application/index/view/Student/scoreDetail.html
- thinkphp/application/index/view/admin_course/courseDetail.html
> 27(studentView pr)

- thinkphp/application/index/controller/MobileController.php
- thinkphp/application/index/controller/TeacherController.php
- thinkphp/application/index/view/Teacher/SignInStudent.html
- thinkphp/application/index/view/Teacher/courseDetail.html
- thinkphp/application/index/view/Teacher/courseStart.html
- thinkphp/application/index/view/Teacher/index.html
- thinkphp/application/index/view/Teacher/signInSeat.html
- thinkphp/application/index/view/admin_course/courseDetail.html
- thinkphp/application/index/view/admin_student/add.html
- thinkphp/application/index/view/admin_student/edit.html
- thinkphp/application/index/view/admin_student/index.html
- thinkphp/application/index/view/mobile/SignInStudent.html
- thinkphp/application/index/view/mobile/courseStart.html
- thinkphp/application/index/view/mobile/index.html
- thinkphp/application/index/view/mobile/signInSeat.html
> signInView

- thinkphp/application/index/view/Teacher/courseAdd.html
- thinkphp/application/index/view/Teacher/courseEdit.html
- thinkphp/application/index/view/Teacher/courseStart.html
- thinkphp/application/index/view/mobile/courseStart.html
> 51 添加课程时间2

- thinkphp/application/index/controller/SigninController.php
- thinkphp/application/index/view/Signin/PasswordConfirmation.html
- thinkphp/application/index/view/Signin/PasswordSignIn.html
- thinkphp/application/index/view/Signin/StudentLogin.html
- thinkphp/application/index/view/Signin/StudentRegister.html
- thinkphp/application/index/view/Signin/index.html
- thinkphp/application/index/view/Signin/nosignin.html
- thinkphp/application/index/view/Signin/verificationCode.html
- thinkphp/application/index/view/index.html
#72
t.com/100888986/158731362-16e3afbd-f1ed-48e3-8e52-b26ab66e7009.png)
888986/158731388-248b353f-0084-486b-b1cc-48e8892c71b7.png)
/100888986/158731369-82079a2e-060f-4dcf-82fb-c9ded1c
a33fe.png)
> 学生扫码后进入的界面（第二次修改）

- application/common/model/User.php
> User表 ，Teacher表， Student表， Admin表之间的ER图

- application/index/controller/IndexController.php
- application/index/controller/MobileController.php
- application/index/view/index.html
- application/index/view/index/courseAdd.html
- application/index/view/index/courseDetail.html
- application/index/view/index/courseEdit.html
- application/index/view/index/courseKlassAdd.html
- application/index/view/index/courseProgramAdd.html
- application/index/view/index/courseProgramEdit.html
- application/index/view/index/courseSort.html
- application/index/view/index/courseStart.html
- application/index/view/index/courseTimeAdd.html
- application/index/view/index/coursing.html
- application/index/view/index/fraction.html
- application/index/view/index/index.html
- application/index/view/index/klass.html
- application/index/view/index/klassImport.html
- application/index/view/index/programEdit.html
- application/index/view/index/randomCode.html
- application/index/view/index/rankEdit.html
- application/index/view/index/signInSeat.html
- application/index/view/index/signInSeatAdd.html
- application/index/view/index/signInStudent.html
- application/index/view/index/signInStudentAdd.html
- application/index/view/index/student.html
- application/index/view/index/studentAdd.html
> index模块模板文件 和 方法名排序

- application/admin/controller/LoginController.php
- application/admin/view/index.html
- application/common/model/User.php
- application/student/controller/LoginController.php
> 登录功能:debug

- application/common/model/Admin.php
- application/common/model/Course.php
- application/common/model/CourseScore.php
- application/common/model/Dispatch.php
- application/common/model/DispatchRoom.php
- application/common/model/Klass.php
- application/common/model/KlassCourse.php
- application/common/model/Program.php
- application/common/model/ProgramScore.php
- application/common/model/Room.php
- application/common/model/Schedule.php
- application/common/model/ScheduleKlass.php
- application/common/model/Sign.php
- application/common/model/Student.php
- application/common/model/StudentSchedule.php
- application/common/model/Teacher.php
- application/common/model/Term.php
- application/common/model/User.php
> M层  1、属性调用前验证 2、类型转换   3、user表获取性别

- application/admin/controller/AdminTeacherController.php
- application/admin/view/admin_teacher/add.html
- application/admin/view/admin_teacher/index.html
- application/common/validate/Teacher.php
- application/common/validate/User.php
> 管理员端的教师管理的添加教师功能

- application/common/model/Dispatch.php
- application/common/model/DispatchRoom.php
- application/common/model/Schedule.php
- application/common/model/Teacher.php
- application/index/controller/IndexController.php
- application/index/view/index/courseAdd.html
- sql/yunzhi_dispatch.sql
- sql/yunzhi_klass.sql
> 教师端排课管理 添加课程

- application/common/model/Dispatch.php
- application/common/model/Schedule.php
- application/common/model/Teacher.php
- application/common/model/Term.php
- application/index/controller/IndexController.php
- application/index/view/index/courseSort.html
> courseSave关联学生 + courseSort页面显示（教师端排课管理） 

- application/admin/controller/AdminTeacherController.php
- application/common/model/Teacher.php
#127 先删除Teacher表中的数据，在通过Teacher表中该条数据的user_id查找到User表中对应数据一并删除。
另外在M层的Teacher.php加入getUserId方法。
> 管理端教师管理的删除

- application/common/model/Course.php
- application/common/model/Program.php
- application/common/model/Schedule.php
- application/common/model/Teacher.php
- application/index/controller/IndexController.php
- application/index/view/index.html
- application/index/view/index/courseDetail.html
- application/index/view/index/courseProgramAdd.html
- application/index/view/index/courseSort.html
- sql/yunzhi_program.sql
> 教师端：排课管理courseDetail页面显示

- application/admin/controller/AdminTeacherController.php
- application/admin/view/admin_teacher/index.html
- application/common/model/Teacher.php
- application/common/model/User.php
但还有3个细节未处理：
1.显示时虽然不显示role !== 1的数据，但在分页里它仍然占一个位置。例如：在未进行查找的显示中，（每页显示为5条数据）若这些数据中有1条数据的role !== 1 ；则该页只显示4条数据。
2.搜索框的回填
3.编辑成功后返回的不是被修改数据的所在页，而是首页。
另外，因需求，在m层的teacher.php中加入了getTeacherIdByUserId的方法。
> 查找功能完成大部分，按姓名查找已完成，按手机号查找还未完成

- application/common/model/Schedule.php
- application/common/model/Teacher.php
- application/index/controller/IndexController.php
- application/index/view/index.html
- application/index/view/index/courseDetail.html
- application/index/view/index/courseKlassAdd.html
- application/index/view/index/courseProgramAdd.html
- application/index/view/index/courseProgramEdit.html
- application/index/view/index/courseScheduleWeek.html
- application/index/view/index/courseSort.html
- application/index/view/index/courseTimeAdd.html
> 教师端 ： 添加项目 添加上课时间 添加上课班级 项目编辑

- application/admin/controller/AdminTeacherController.php
- application/admin/view/admin_teacher/edit.html
- application/admin/view/admin_teacher/index.html
> 管理员端教师管理查找功能已完善

- application/admin/controller/AdminStudentController.php
- application/admin/view/admin_student/index.html
- application/common/model/Student.php
> 管理员端学生管理的删除功能

- application/admin/controller/AdminStudentController.php
- application/common/model/Student.php
- sql/yunzhi_student.sql
> 管理端学生管理查询功能，按姓名、学号查询已完成，按班级查询未实现

- application/common/model/Teacher.php
- application/index/view/index/courseScheduleTerm.html
- runtime/temp/3dc6ef2d55c6565aac914b507d53838a.php
- runtime/temp/40f5d1efc36847d2b36aea85816ba71f.php
- runtime/temp/76bafd8a14fbec69df6d091e1cc4e98d.php
- runtime/temp/9101e4b25bf80a5ec57c7a325244da1b.php
- runtime/temp/ae8dcc0c057d461a5def246c7042e163.php
- runtime/temp/dbc1d1bc52982febb4d24bf8b77259c8.php
- runtime/temp/e3fff1fbc1a88f60f17e3ee1f4eead2f.php
- runtime/temp/fca701a6491d9e95e0fc5b1a9f8174a4.php
> 课程编辑界面动态显示bug修改

- application/admin/controller/AdminStudentController.php
- application/admin/controller/AdminTeacherController.php
- application/admin/controller/AdminTermController.php
- application/admin/view/admin_student/edit.html
- application/admin/view/admin_teacher/edit.html
- application/admin/view/admin_term/edit.html
- application/admin/view/personal/edit.html
- application/common/model/Student.php
- application/common/model/StudentSchedule.php
- application/common/model/Term.php
- application/common/model/User.php
- application/common/validate/User.php
> 管理端：学期管理和教室管理的编辑功能,  修改了学生管理的新增功能

- application/admin/controller/AdminKlassController.php
- application/admin/controller/AdminStudentController.php
- application/admin/view/admin_klass/edit.html
- application/admin/view/admin_klass/index.html
- application/admin/view/admin_klass/klassMembers.html
- application/admin/view/admin_klass/studentAdd.html
- application/admin/view/admin_student/edit.html
- application/admin/view/admin_student/index.html
- application/common/model/Klass.php
- application/common/model/Student.php
- application/common/model/StudentSchedule.php
- application/common/model/User.php
- application/common/validate/Room.php
- application/common/validate/Student.php
> 教师端：班级模块编辑 + 学生模块编辑修改

- application/index/controller/VueController.php
- application/index/view/schedule/scheduleAdd.html
当前功能：
1、根据已经选择的课程找出没有选择过该课程的班级进行循环
2、根据已经选择的班级和当前的教师判断冲突的时间
下一步：
通过冲突时间（在根组件）在每个course-select-time组件中求出可以选择的时间（或者是不可以选择的时间）
> 课程表：班级选择组件 和 课程时间组件

- application/index/controller/VueController.php
- application/index/view/schedule/scheduleAdd.html
#190 还存在bug : 多选周数或教室时，暂时还没法同步过滤，单条数据之间的过滤还存在影响。
> 周数和教室的冲突，引入动态数据，循环输出

- application/index/controller/ScheduleController.php
- application/index/controller/VueController.php
- application/index/controller/test.js
- application/index/view/schedule/scheduleAdd.html
> 添加排课：后台整合调度信息以及前台获取后 course-time-select组件第一步筛选

- application/index/controller/VueController.php
- application/index/view/schedule/scheduleAdd.html
> 添加排课：学期条件约束

- application/index/controller/test.js
- application/index/view/schedule/scheduleAdd.html
> 选择周数筛选教室功能已完成

- application/index/view/schedule/scheduleAdd.html
> 选择教室筛选周数功能已完成

- application/index/controller/VueController.php
- application/index/controller/test.js
- application/index/view/schedule/scheduleAdd.html
解决之前的教室只考虑当前教师和已选择教班级所对应的冲突数据
教室的冲突应该是无论是哪位教师，选择的哪些班级 都应该有共同的冲突教室。
> 添加排课：bug修复2

- application/index/view/schedule/scheduleAdd.html
#188 
修复虽然roomids是当前周天节的全部冲突教室，但是因为有教师的筛选，所以并没有获取对象，也就没有获取roomids的bug
> 添加排课：bug修复3

- application/common/model/Dispatch.php
- application/index/controller/VueController.php
- application/index/view/schedule/courseDetail.html
- application/index/view/schedule/scheduleAdd.html
> 对接dontDisplayWeeks数据，课程详情的周几几节使用0基显示

- application/index/controller/VueController.php
- application/index/view/schedule/scheduleAdd.html
- application/index/view/test/index.html
> 添加排课：同时只能显示一个选择时间的小单元的功能

- application/index/view/schedule/scheduleAdd.html
> bug修复：已选项在小单元重启之后仍在勾选状态

- application/index/controller/ScheduleController.php
- application/index/controller/VueController.php
- application/index/view/schedule/scheduleAdd.html
> 添加排课：从v层获取的需要进行添加的值

- application/admin/controller/AdminStudentController.php
- application/admin/controller/AdminTeacherController.php
- application/admin/view/admin_student/index.html
修复  教师管理删除找不到id，教师编辑中保存后提示密码不符合限制，学生管理按班级查询的回填，
> 完善管理员端一些细节

- application/index/controller/IndexController.php
- application/index/view/schedule/courseTimeAdd.html
- application/index/view/test/test.html
> 在编辑排课中，添加排课时间界面添加上课班级的显示，并在此界面引入弹出模态框，但还有bug（修复后再在添加排课中引用）

- application/index/view/schedule/courseTimeAdd.html
- application/index/view/schedule/scheduleAdd.html
> 弹出模态框bug已修复，在编辑排课中的添加排课时间界面和添加排课界面引入弹出模态框

- application/common/model/Dispatch.php
- application/common/model/Klass.php
- application/common/model/ScheduleKlass.php
- application/index/controller/ScheduleController.php
- application/index/view/schedule/courseTimeAdd.html
> 编辑排课：添加上课班级中的可选班级过滤了与当前排课的上课时间冲突的班级（不显示）

- application/common/model/Schedule.php
- application/common/model/Teacher.php
- application/index/controller/ScheduleController.php
- application/index/view/schedule/courseKlassAdd.html
- application/index/view/schedule/courseTimeAdd.html
#226 
编辑排课功能+教师端排课管理编辑后班级删除时同时也应该删除student_schedule表中这个班级的学生的bug
> 编辑排课的功能实现+bug修复

- application/common/model/Dispatch.php
- application/index/controller/ScheduleController.php
- application/index/controller/VueController.php
- application/index/view/schedule/courseTimeAdd.html
- application/index/view/schedule/scheduleAdd.html
> 添加上课班级的对多项冲突时间的循环筛选，添加上课时间中不可选周数加上了一层已选班级的冲突过滤

- .idea/modules.xml
- .idea/sign-in-through-code-scanning.iml
- .idea/vcs.xml
- .idea/workspace.xml
- api/application/index/controller/LoginController.php
- web/first-app/src/app/admin/pipe/term-state.pipe.ts
- web/first-app/src/app/admin/teacher/teacher-add/teacher-add.component.ts
- web/first-app/src/app/admin/term/add/term-add.component.html
- web/first-app/src/app/admin/term/add/term-add.component.ts
- web/first-app/src/app/admin/term/edit/term-edit.component.html
- web/first-app/src/app/admin/term/edit/term-edit.component.ts
- web/first-app/src/app/admin/term/index/term-index.component.html
- web/first-app/src/app/admin/term/index/term-index.component.ts
- web/first-app/src/app/app-routing.module.ts
- web/first-app/src/app/app.module.ts
- web/first-app/src/app/entity/term.spec.ts
- web/first-app/src/app/entity/term.ts
- web/first-app/src/app/mock-api/term.mock.api.ts
#234 
todo: index 分页功能
暂未从thinkphp api 请求数据
> 学期管理add 和 edit 界面

- web/first-app/src/app/admin/admin.module.ts
- web/first-app/src/app/admin/room/room-add/room-add.component.html
- web/first-app/src/app/admin/room/room-add/room-add.component.spec.ts
- web/first-app/src/app/admin/room/room-add/room-add.component.ts
- web/first-app/src/app/admin/room/room-edit/room-edit.component.html
- web/first-app/src/app/admin/room/room-edit/room-edit.component.spec.ts
- web/first-app/src/app/admin/room/room-edit/room-edit.component.ts
- web/first-app/src/app/admin/room/room-index/room-index.component.html
> 教室管理edit和add

- web/first-app/src/app/admin/admin.module.ts
- web/first-app/src/app/admin/personal/personal-edit/personal-edit.component.html
- web/first-app/src/app/admin/personal/personal-edit/personal-edit.component.spec.ts
- web/first-app/src/app/admin/personal/personal-edit/personal-edit.component.ts
- web/first-app/src/app/admin/personal/personal-index/personal-index.component.html
- web/first-app/src/app/admin/personal/personal-index/personal-index.component.spec.ts
- web/first-app/src/app/admin/personal/personal-index/personal-index.component.ts
- web/first-app/src/app/admin/personal/personal.module.ts
- web/first-app/src/app/nav/nav.component.html
> 个人中心index和edit

- web/first-app/src/app/app-routing.module.ts
- web/first-app/src/app/student/sign-in-affirm/sign-in-affirm.component.html
- web/first-app/src/app/student/sign-in-affirm/sign-in-affirm.component.spec.ts
- web/first-app/src/app/student/sign-in-affirm/sign-in-affirm.component.ts
- web/first-app/src/app/student/sign-in-index/sign-in-index.component.html
- web/first-app/src/app/student/sign-in-index/sign-in-index.component.spec.ts
- web/first-app/src/app/student/sign-in-index/sign-in-index.component.ts
- web/first-app/src/app/student/sign-in-signal/sign-in-signal.component.html
- web/first-app/src/app/student/sign-in-signal/sign-in-signal.component.spec.ts
- web/first-app/src/app/student/sign-in-signal/sign-in-signal.component.ts
- web/first-app/src/app/student/sign-in-success/sign-in-success.component.html
- web/first-app/src/app/student/sign-in-success/sign-in-success.component.spec.ts
- web/first-app/src/app/student/sign-in-success/sign-in-success.component.ts
- web/first-app/src/app/student/student-routing.module.ts
- web/first-app/src/app/student/student.module.ts
> student模块原型

- web/first-app/src/app/admin/clazz/clazz-select/clazz-select.component.html
- web/first-app/src/app/admin/clazz/clazz-select/clazz-select.component.spec.ts
- web/first-app/src/app/admin/clazz/clazz-select/clazz-select.component.ts
- web/first-app/src/app/admin/clazz/clazz.module.ts
- web/first-app/src/app/mock-api/clazz.mock.api.ts
- web/first-app/src/app/mock-api/mock-api-testing.module.ts
> ClazzSelectComponent

- package-lock.json
- web/first-app/src/app/admin/room/room-index/room-index.component.html
- web/first-app/src/app/admin/room/room-index/room-index.component.ts
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.html
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.ts
- web/first-app/src/app/entity/room.ts
- web/first-app/src/app/mock-api/mock-api-testing.module.ts
- web/first-app/src/app/mock-api/room.mock.api.ts
- web/first-app/src/app/mock-api/teacher.mock.api.ts
- web/first-app/src/app/service/menu.service.ts
> teacher和room的mock-apiâ

- web/first-app/src/app/admin/admin.module.ts
- web/first-app/src/app/admin/clazz/clazz-index/clazz-index.component.html
- web/first-app/src/app/admin/clazz/clazz-index/clazz-index.component.ts
- web/first-app/src/app/admin/clazz/clazz.module.ts
- web/first-app/src/app/admin/personal/personal-index/personal-index.component.html
- web/first-app/src/app/admin/room/room-add/room-add.component.html
- web/first-app/src/app/admin/room/room-edit/room-edit.component.html
- web/first-app/src/app/admin/room/room-index/room-index.component.html
- web/first-app/src/app/admin/room/room-index/room-index.component.ts
- web/first-app/src/app/admin/room/room-routing.module.ts
- web/first-app/src/app/admin/room/room.module.ts
- web/first-app/src/app/admin/student/student-index/student-index.component.html
- web/first-app/src/app/admin/student/student-index/student-index.module.ts
- web/first-app/src/app/admin/teacher/teacher-add/teacher-add.component.html
- web/first-app/src/app/admin/teacher/teacher-edit/teacher-edit.component.html
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.html
- web/first-app/src/app/admin/teacher/teacher.module.ts
- web/first-app/src/app/entity/room.ts
- web/first-app/src/app/mock-api/clazz.mock.api.ts
- web/first-app/src/app/mock-api/mock-api-testing.module.ts
- web/first-app/src/app/mock-api/room.mock.api.ts
- web/first-app/src/app/mock-api/teacher.mock.api.ts
- web/first-app/src/app/service/menu.service.ts
> 管理端班级管理的完善+debug

- web/first-app/src/app/admin/clazz/clazz-index/clazz-index.component.spec.ts
- web/first-app/src/app/admin/room/room-index/room-index.component.spec.ts
- web/first-app/src/app/admin/room/room.module.ts
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.spec.ts
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.module.ts
- web/first-app/src/app/admin/teacher/teacher.module.ts
- web/first-app/src/app/teacher/task/task-routing.module.ts
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.component.html
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.component.spec.ts
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.component.ts
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.module.ts
- web/first-app/src/app/teacher/task/view-student/view-student.component.html
> debug: 添加pageModule   + 解决ng t报错

- web/first-app/angular.json
- web/first-app/src/app/teacher/task/course-start/course-start.component.html
- web/first-app/src/app/teacher/task/course-start/course-start.component.ts
- web/first-app/src/app/teacher/task/sign-in-state/sign-in-state.component.html
- web/first-app/src/app/teacher/task/sign-in-state/sign-in-state.component.spec.ts
- web/first-app/src/app/teacher/task/sign-in-state/sign-in-state.component.ts
- web/first-app/src/app/teacher/task/sign-in-state/sign-in-state.module.ts
- web/first-app/src/app/teacher/task/task-routing.module.ts
- web/first-app/src/app/teacher/task/task.module.ts
> 教师端=>课程任务=>开始上课中的一些界面

- web/first-app/src/app/entity/course.ts
- web/first-app/src/app/mock-api/course.mock.api.ts
- web/first-app/src/app/mock-api/mock-api-testing.module.ts
- web/first-app/src/app/teacher/course/course-index/course-index.component.html
- web/first-app/src/app/teacher/course/course-index/course-index.component.ts
- web/first-app/src/app/teacher/course/course.module.ts
> 课程管理-》mock-api、debug

- web/first-app/src/app/entity/schedule.ts
- web/first-app/src/app/mock-api/schedule.mock.api.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/program-add/program-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/program-add/program-add.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/program-add/program-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.html
- web/first-app/src/app/teacher/schedule/schedule-routing.module.ts
- web/first-app/src/app/teacher/schedule/schedule.module.ts
- web/first-app/src/app/teacher/teacher.module.ts
> 原型-》教师端-》排课管理-》edit-index及add

- api/application/index/controller/LoginController.php
- web/first-app/angular.json
- web/first-app/src/app/admin/admin-routing.module.ts
- web/first-app/src/app/app-routing.module.ts
- web/first-app/src/app/app.module.ts
- web/first-app/src/app/index/index.component.html
- web/first-app/src/app/index/index.component.ts
- web/first-app/src/app/login/login.component.html
- web/first-app/src/app/login/login.component.ts
- web/first-app/src/app/teacher/task/task-index/task-index.module.ts
- web/first-app/src/app/teacher/teacher-routing.module.ts
- web/first-app/src/index.html
> debug: 学生端通过导航进入签到界面

- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/name-edit/name-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/name-edit/name-edit.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/name-edit/name-edit.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/program-edit/program-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/program-edit/program-edit.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/program-edit/program-edit.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.html
- web/first-app/src/app/teacher/schedule/schedule-routing.module.ts
- web/first-app/src/app/teacher/schedule/schedule.module.ts
> 原型-》教师端-》排课管理-》添加排课、排课edit及其中的edit

- api/application/api/controller/RoomController.php
- web/first-app/src/app/admin/room/room-index/room-index.component.ts
- web/first-app/src/app/service/room.service.ts
- web/first-app/src/app/teacher/teacher.module.ts
> 管理åå端-》教室管理-》indexè¯向php后台请ä请求数据

- api/application/api/controller/TeacherController.php
- api/application/api/controller/TermController.php
- web/first-app/src/app/service/teacher.service.ts
- web/first-app/src/app/service/term.service.ts
- web/first-app/src/app/service/user.service.ts
> Observable to pipe; thinkphp page()

- api/application/api/controller/RoomController.php
- api/application/api/controller/TermController.php
- api/application/common/model/Room.php
- web/first-app/src/app/admin/room/room-add/room-add.component.html
- web/first-app/src/app/admin/room/room-add/room-add.component.ts
- web/first-app/src/app/admin/room/room-index/room-index.component.html
- web/first-app/src/app/admin/room/room-index/room-index.component.ts
- web/first-app/src/app/admin/room/room.module.ts
- web/first-app/src/app/admin/term/add/term-add.component.ts
- web/first-app/src/app/service/room.service.ts
- web/first-app/src/app/service/term.service.ts
> 管理端-》教室管理-》删除和添加功能

- api/application/api/controller/StudentController.php
- web/first-app/package-lock.json
- web/first-app/package.json
- web/first-app/src/app/admin/clazz/clazz-select/clazz-select.component.html
- web/first-app/src/app/admin/clazz/clazz-select/clazz-select.component.ts
- web/first-app/src/app/admin/student/student-add/student-add.component.html
- web/first-app/src/app/admin/student/student-add/student-add.component.ts
- web/first-app/src/app/admin/student/student-add/student-add.module.ts
- web/first-app/src/app/admin/student/student-edit/student-edit.component.html
- web/first-app/src/app/admin/student/student-edit/student-edit.component.ts
- web/first-app/src/app/admin/student/student-edit/student-edit.module.ts
- web/first-app/src/app/admin/student/student-index/student-index.component.html
- web/first-app/src/app/admin/student/student-index/student-index.component.ts
- web/first-app/src/app/admin/student/student.module.ts
- web/first-app/src/app/app.module.ts
- web/first-app/src/app/mock-api/student.mock.api.ts
- web/first-app/src/app/service/common.service.spec.ts
- web/first-app/src/app/service/common.service.ts
- web/first-app/src/app/service/student.service.ts
> admin-》student功能

- api/application/api/controller/RoomController.php
- web/first-app/src/app/admin/room/room-add/room-add.component.ts
- web/first-app/src/app/admin/room/room-edit/room-edit.component.html
- web/first-app/src/app/admin/room/room-edit/room-edit.component.ts
- web/first-app/src/app/admin/term/edit/term-edit.component.ts
- web/first-app/src/app/service/room.service.ts
> admin->room->edit功能

- api/application/api/controller/StudentController.php
- api/application/common/model/User.php
- web/first-app/src/app/admin/clazz/clazz-mebers-edit/clazz-mebers-edit.component.ts
- web/first-app/src/app/admin/clazz/clazz-mebers-edit/clazz-members-edit.component.html
- web/first-app/src/app/admin/clazz/clazz-mebers-edit/clazz-members-edit.component.spec.ts
- web/first-app/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.html
- web/first-app/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.spec.ts
- web/first-app/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.ts
- web/first-app/src/app/admin/clazz/clazz-members/clazz-members.component.html
- web/first-app/src/app/admin/clazz/clazz-members/clazz-members.component.ts
- web/first-app/src/app/admin/clazz/clazz-routing.module.ts
- web/first-app/src/app/admin/clazz/clazz-select/clazz-select.component.html
- web/first-app/src/app/admin/room/room-add/room-add.component.spec.ts
- web/first-app/src/app/admin/room/room-edit/room-edit.component.spec.ts
- web/first-app/src/app/admin/student/student-edit/student-edit.component.html
- web/first-app/src/app/admin/student/student-edit/student-edit.component.ts
- web/first-app/src/app/admin/student/student-index/student-index.component.html
- web/first-app/src/app/admin/student/student-index/student-index.component.ts
- web/first-app/src/app/admin/student/student-update-password/student-update-password.component.spec.ts
- web/first-app/src/app/service/student.service.ts
> 管理端 => 学生管理功能debug + 班级管理功能实现

- api/application/api/controller/ScheduleController.php
- web/first-app/src/app/mock-api/schedule.mock.api.ts
- web/first-app/src/app/service/schedule.service.spec.ts
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.html
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.ts
> teacher端-》排课管理-》index功能

- api/application/api/controller/ScheduleController.php
- api/application/api/controller/StudentController.php
- web/first-app/src/app/admin/clazz/clazz-mebers-edit/clazz-mebers-edit.component.ts
- web/first-app/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.ts
- web/first-app/src/app/admin/clazz/clazz-members/clazz-members.component.html
- web/first-app/src/app/admin/student/student-add/student-add.component.ts
- web/first-app/src/app/admin/student/student-edit/student-edit.component.ts
- web/first-app/src/app/admin/student/student-index/student-index.component.html
- web/first-app/src/app/admin/student/student-index/student-index.component.ts
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.html
- web/first-app/src/app/entity/schedule.ts
- web/first-app/src/app/entity/schedule_klass.ts
- web/first-app/src/app/entity/student.ts
- web/first-app/src/app/entity/teacher.ts
- web/first-app/src/app/mock-api/schedule.mock.api.ts
- web/first-app/src/app/mock-api/student.mock.api.ts
- web/first-app/src/app/service/schedule.service.spec.ts
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/service/student.service.ts
- web/first-app/src/app/teacher/course/course-add/course-add.component.spec.ts
- web/first-app/src/app/teacher/course/course-edit/course-edit.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.html
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.ts
- web/first-app/src/app/teacher/task/task-index/task-index.component.html
- web/first-app/src/app/teacher/task/view-student/view-student.component.html
> entity修改, teacher->schedule->index

- api/application/api/controller/CourseController.php
- api/application/api/controller/RoomController.php
- web/first-app/src/app/service/course.service.ts
- web/first-app/src/app/teacher/course/course-edit/course-edit.component.html
- web/first-app/src/app/teacher/course/course-edit/course-edit.component.ts
- web/first-app/src/app/teacher/course/course-index/course-index.component.html
- web/first-app/src/app/teacher/course/course-index/course-index.component.ts
- web/first-app/src/app/teacher/course/course-routing.module.ts
- web/package-lock.json
> teacher->course->edit and delete 

- api/application/api/controller/CourseController.php
- web/first-app/src/app/service/course.service.ts
- web/first-app/src/app/teacher/course/course-index/course-index.component.html
- web/first-app/src/app/teacher/course/course-index/course-index.component.ts
可按输入条件查询，但存在bug：当查询数据数不足一页时，查询后分页仍然显示总页数，点击其他页后查询效果消失
> teacher->course->查询功能

- api/application/api/controller/ClazzController.php
- web/first-app/src/app/admin/clazz/clazz-members/clazz-members.component.html
- web/first-app/src/app/admin/clazz/clazz-members/clazz-members.component.ts
- web/first-app/src/app/service/clazz.service.ts
> 管理端=>班级管理=>查看成员debug

- api/application/api/controller/CourseController.php
- api/application/api/controller/DispatchController.php
- api/application/api/controller/ProgramController.php
- api/application/api/controller/ScheduleController.php
- api/application/common/model/Dispatch.php
- api/application/common/validate/Program.php
- web/first-app/src/app/admin/term/edit/term-edit.component.ts
- web/first-app/src/app/login/login.component.ts
- web/first-app/src/app/service/dispatch.service.ts
- web/first-app/src/app/service/program.service.ts
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/teacher/course/course-index/course-index.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/name-edit/name-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/name-edit/name-edit.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/program-add/program-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/program-add/program-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/program-edit/program-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/program-edit/program-edit.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.ts
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.html
- web/first-app/src/app/teacher/schedule/schedule-index/schedule-index.component.ts
- web/first-app/src/app/teacher/schedule/schedule-routing.module.ts
> 教师端=>排课管理=>edit=>添加上课时间，添加上课班级之外的功能

- api/application/api/controller/StudentScheduleController.php
- web/first-app/src/app/service/studentSchedule.service.ts
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.component.html
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.component.ts
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.module.ts
> 教师端课程任务查看学生新增

- api/application/api/controller/TeacherController.php
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.html
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.component.ts
- web/first-app/src/app/admin/teacher/teacher-index/teacher-index.module.ts
- web/first-app/src/app/service/teacher.service.ts
> admin-》教师管理查询

- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.spec.ts
- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.ts
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule.module.ts
- web/first-app/src/app/teacher/task/view-student-add/view-student-add.module.ts
> 排课功能： 课程班级和小单元分组件

- api/application/api/controller/ClazzController.php
- api/application/api/controller/ScheduleController.php
- web/first-app/src/app/service/clazz.service.ts
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.ts
- web/first-app/src/app/teacher/schedule/schedule-add/readme.txt
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.ts
> 添加排课功能初步开发

- api/application/api/controller/ScheduleController.php
- api/application/api/controller/TeacherController.php
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/service/teacher.service.ts
- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/course-time/course-time.component.ts
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-add/schedule-add.component.ts
> 新增排课，可成功添加数据，但存在某些bug待修复

- api/application/api/controller/ScheduleController.php
- web/first-app/src/app/service/clazz.service.ts
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/schedule-edit.component.ts
> 编辑排课-》添加课程-》save 与 delete （解决合并冲突）

- web/first-app/src/app/nav/nav.component.html
- web/first-app/src/app/service/menu.service.ts
- web/first-app/src/app/student/sign-in-affirm/sign-in-affirm.component.html
- web/first-app/src/app/student/sign-in-index/sign-in-index.component.html
- web/first-app/src/app/student/sign-in-signal/sign-in-signal.component.html
- web/first-app/src/app/student/sign-in-success/sign-in-success.component.html
- web/first-app/src/index.html
> 学生端的一些html改动

- api/application/api/controller/CourseScheduleController.php
- api/application/api/controller/ScheduleController.php
- api/application/api/controller/TermController.php
- api/application/common/model/Teacher.php
- web/first-app/src/app/nav/nav.component.html
- web/first-app/src/app/service/courseSchedule.service.ts
- web/first-app/src/app/service/menu.service.ts
- web/first-app/src/app/service/term.service.ts
- web/first-app/src/app/student/sign-in-affirm/sign-in-affirm.component.html
- web/first-app/src/app/student/sign-in-index/sign-in-index.component.html
- web/first-app/src/app/student/sign-in-signal/sign-in-signal.component.html
- web/first-app/src/app/student/sign-in-success/sign-in-success.component.html
- web/first-app/src/app/teacher/clazz-schedule/term-schedule/term-schedule.component.html
- web/first-app/src/app/teacher/clazz-schedule/week-schedule/week-schedule.component.html
- web/first-app/src/app/teacher/clazz-schedule/week-schedule/week-schedule.component.ts
- web/first-app/src/app/teacher/clazz-schedule/week-schedule/week-schedule.module.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.html
- web/first-app/src/index.html
> 课程表（学习课程表还未完成）

- api/application/api/controller/ScheduleController.php
- api/application/common/model/Dispatch.php
- api/application/common/model/Schedule.php
- web/first-app/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.ts
> 实现同一天同一节不同周可在不同的一个或几个教室上课的功能 添加排课debug

- api/application/common/model/Schedule.php
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.ts
> scheduleEdit->timeAdd->debug

- api/application/common/model/Schedule.php
- web/first-app/src/app/service/schedule.service.ts
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.html
- web/first-app/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.ts
操作提示：对于周数和教室均有已选的小单元：
(1)新勾选周数和新勾选教室=>新勾选的周数在新勾引的教室上课
(2)只新勾选周数=>新勾选的周数在所有已勾选的教室上课
(3)只新勾选教室=>新勾选的教室添加到所有已勾选周数的地点信息中
(4)只取消勾选周数=>删除对应天、节、周的调度信息
(5)只取消勾选教室=>含有此教室的调度的地点信息删除此教室，若此教室为唯一地点信息，则此条调度信息将被删除
(6)其他=>不支持此类操作，请返回上个界面进行删除操作
> scheduleEdit->timeAdd->完善一些问题，加一些操作提示

- api/application/api/controller/UserController.php
- api/application/common/model/User.php
- web/first-app/src/app/admin/admin-routing.module.ts
- web/first-app/src/app/admin/admin.module.ts
- web/first-app/src/app/admin/personal/personal-edit/personal-edit.component.html
- web/first-app/src/app/admin/site/site-index/site-index.component.html
- web/first-app/src/app/admin/site/site-index/site-index.component.spec.ts
- web/first-app/src/app/admin/site/site-index/site-index.component.ts
- web/first-app/src/app/admin/site/site-routing.module.ts
- web/first-app/src/app/admin/site/site.module.ts
- web/first-app/src/app/admin/site/update-student-index-password/update-student-index-password.component.html
- web/first-app/src/app/admin/site/update-student-index-password/update-student-index-password.component.spec.ts
- web/first-app/src/app/admin/site/update-student-index-password/update-student-index-password.component.ts
- web/first-app/src/app/admin/site/update-teacher-index-password/update-teacher-index-password.component.html
- web/first-app/src/app/admin/site/update-teacher-index-password/update-teacher-index-password.component.spec.ts
- web/first-app/src/app/admin/site/update-teacher-index-password/update-teacher-index-password.component.ts
- web/first-app/src/app/admin/student/student-add/student-add.component.html
- web/first-app/src/app/admin/student/student-add/student-add.component.ts
- web/first-app/src/app/admin/teacher/teacher-add/teacher-add.component.html
- web/first-app/src/app/admin/teacher/teacher-add/teacher-add.component.ts
- web/first-app/src/app/service/menu.service.ts
- web/first-app/src/app/service/user.service.ts
> 管理端增加系统设置，可修改默认的教师密码和学生密码

- api/.jpb/persistence-units.xml
- api/src/main/java/com/example/api/controller/UserController.java
- api/src/main/java/com/example/api/respositoty/UserRepository.java
- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/app/interceptor/api.interceptor.ts
- web/src/app/login/login.component.ts
- web/src/app/service/user.service.ts
> 简单通过用户名密码的登陆

- .github/workflows/spring-boot.yml
- api/pom.xml
- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/RoomController.java
- api/src/main/java/com/example/api/entity/Admin.java
- api/src/main/java/com/example/api/entity/Klass.java
- api/src/main/java/com/example/api/entity/Room.java
- api/src/main/java/com/example/api/entity/Student.java
- api/src/main/java/com/example/api/entity/Teacher.java
- api/src/main/java/com/example/api/entity/User.java
- api/src/main/java/com/example/api/repository/RoomRepository.java
- api/src/main/java/com/example/api/repository/specs/RoomSpecs.java
- api/src/main/java/com/example/api/service/RoomService.java
- api/src/main/java/com/example/api/service/RoomServiceImpl.java
- api/src/test/java/com/example/api/controller/RoomControllerTest.java
- api/src/test/java/com/example/api/repository/RoomRepositoryTest.java
- api/src/test/java/com/example/api/service/RoomServiceImplTest.java
- web/package-lock.json
- web/src/app/admin/room/room-index/room-index.component.ts
- web/src/app/app.module.ts
- web/src/app/entity/page.ts
- web/src/app/login/login.component.ts
- web/src/app/mock-api/mock-api-testing.module.ts
- web/src/app/mock-api/user.mock.api.ts
- web/src/app/service/room.service.ts
> 后台 => admin => room 增 查 删

- .github/workflows/spring-boot.yml
> angular test

- api/pom.xml
- api/src/main/java/com/example/api/controller/TermController.java
- api/src/main/java/com/example/api/repository/TermRepository.java
- api/src/main/java/com/example/api/repository/specs/TermSpecs.java
- api/src/main/java/com/example/api/service/TermService.java
- api/src/main/java/com/example/api/service/TermServiceImpl.java
- api/src/test/java/com/example/api/controller/TermControllerTest.java
- api/src/test/java/com/example/api/service/TermServiceImplTest.java
> 分页，删除，单元测试

- api/src/main/java/com/example/api/controller/TermController.java
- api/src/main/java/com/example/api/entity/Term.java
- api/src/main/java/com/example/api/service/TermService.java
- api/src/main/java/com/example/api/service/TermServiceImpl.java
- api/src/test/java/com/example/api/controller/TermControllerTest.java
- api/src/test/java/com/example/api/service/TermServiceImplTest.java
- web/package-lock.json
- web/src/app/admin/term/index/term-index.component.html
- web/src/app/service/term.service.ts
- web/src/app/service/user.service.ts
> 管理端-》学期管理-》编辑、激活

- api/pom.xml
- api/src/main/java/com/example/api/controller/RoomController.java
- api/src/main/java/com/example/api/entity/Term.java
- api/src/main/java/com/example/api/service/RoomService.java
- api/src/main/java/com/example/api/service/RoomServiceImpl.java
- api/src/test/java/com/example/api/controller/RoomControllerTest.java
- api/src/test/java/com/example/api/controller/TermControllerTest.java
- api/src/test/java/com/example/api/service/RoomServiceImplTest.java
- api/src/test/java/com/example/api/service/TermServiceImplTest.java
- web/src/app/service/room.service.ts
> 教室管理 =》 编辑

- api/src/main/java/com/example/api/controller/TermController.java
- api/src/main/java/com/example/api/repository/TermRepository.java
- api/src/main/java/com/example/api/service/TermService.java
- api/src/main/java/com/example/api/service/TermServiceImpl.java
- web/src/app/admin/term/add/term-add.component.html
- web/src/app/admin/term/edit/term-edit.component.html
- web/src/app/validator/common-validator.ts
> 管理端-》学期管理-》激活、学期名称唯一验证

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/TeacherController.java
- api/src/main/java/com/example/api/controller/UserController.java
- api/src/main/java/com/example/api/entity/Teacher.java
- api/src/main/java/com/example/api/entity/User.java
- api/src/main/java/com/example/api/repository/TeacherRepository.java
- api/src/main/java/com/example/api/repository/UserRepository.java
- api/src/main/java/com/example/api/repository/specs/TeacherSpecs.java
- api/src/main/java/com/example/api/repository/specs/UserSpecs.java
- api/src/main/java/com/example/api/service/TeacherService.java
- api/src/main/java/com/example/api/service/TeacherServiceImpl.java
- api/src/main/java/com/example/api/service/UserService.java
- api/src/main/java/com/example/api/service/UserServiceImpl.java
- api/src/test/java/com/example/api/controller/TeacherControllerTest.java
- api/src/test/java/com/example/api/repository/TeacherRepositoryTest.java
- api/src/test/java/com/example/api/repository/specs/RoomSpecsTest.java
- api/src/test/java/com/example/api/repository/specs/TeacherSpecsTest.java
- api/src/test/java/com/example/api/service/TeacherServiceImplTest.java
- web/src/app/admin/teacher/teacher-index/teacher-index.component.ts
- web/src/app/admin/term/index/term-index.component.ts
- web/src/app/entity/user.ts
- web/src/app/index/index.component.ts
- web/src/app/login/login.component.ts
- web/src/app/nav/nav.component.ts
- web/src/app/page/page.component.ts
- web/src/app/service/teacher.service.ts
- web/src/app/service/term.service.ts
> 管理段教师管理 增 查 删

- api/src/main/java/com/example/api/controller/KlassController.java
- api/src/main/java/com/example/api/controller/TermController.java
- api/src/main/java/com/example/api/repository/KlassRepository.java
- api/src/main/java/com/example/api/repository/specs/KlassSpecs.java
- api/src/main/java/com/example/api/service/KlassService.java
- api/src/main/java/com/example/api/service/KlassServiceImpl.java
- api/src/test/java/com/example/api/controller/KlassControllerTest.java
- api/src/test/java/com/example/api/service/KlassServiceImplTest.java
- api/src/test/java/com/example/api/service/TermServiceImplTest.java
- web/src/app/service/clazz.service.ts
> admin->class->新增、删除、查询

- api/src/main/java/com/example/api/controller/TeacherController.java
- api/src/main/java/com/example/api/repository/TeacherRepository.java
- api/src/main/java/com/example/api/service/TeacherService.java
- api/src/main/java/com/example/api/service/TeacherServiceImpl.java
- api/src/test/java/com/example/api/controller/TeacherControllerTest.java
- api/src/test/java/com/example/api/service/TeacherServiceImplTest.java
- web/src/app/admin/teacher/teacher-edit/teacher-edit.component.html
- web/src/app/admin/teacher/teacher-edit/teacher-edit.component.ts
- web/src/app/admin/teacher/teacher-update-password/teacher-update-password.component.ts
- web/src/app/service/teacher.service.ts
> 管理段=>教师管理=>改（修改密码， 修改信息）

- api/src/main/java/com/example/api/controller/KlassController.java
- api/src/main/java/com/example/api/service/KlassService.java
- api/src/main/java/com/example/api/service/KlassServiceImpl.java
- api/src/main/java/com/example/api/service/TermServiceImpl.java
- api/src/test/java/com/example/api/controller/KlassControllerTest.java
- api/src/test/java/com/example/api/repository/KlassRepositoryTest.java
- api/src/test/java/com/example/api/repository/TermRepositoryTest.java
- api/src/test/java/com/example/api/service/KlassServiceImplTest.java
- api/src/test/java/com/example/api/service/TermServiceImplTest.java
- web/src/app/admin/clazz/clazz-add/clazz-add.component.html
- web/src/app/admin/clazz/clazz-edit/clazz-edit.component.html
- web/src/app/service/clazz.service.ts
- web/src/app/validator/common-validator.ts
> admin->class->编辑、班级姓名唯一验证

- api/src/main/java/com/example/api/controller/KlassController.java
- api/src/main/java/com/example/api/controller/UserController.java
- api/src/main/java/com/example/api/service/KlassService.java
- api/src/main/java/com/example/api/service/KlassServiceImpl.java
- api/src/main/java/com/example/api/service/TermServiceImpl.java
- api/src/main/java/com/example/api/service/UserService.java
- api/src/main/java/com/example/api/service/UserServiceImpl.java
- api/src/test/java/com/example/api/controller/KlassControllerTest.java
- api/src/test/java/com/example/api/repository/KlassRepositoryTest.java
- api/src/test/java/com/example/api/repository/TermRepositoryTest.java
- api/src/test/java/com/example/api/service/KlassServiceImplTest.java
- api/src/test/java/com/example/api/service/TermServiceImplTest.java
- web/src/app/admin/clazz/clazz-add/clazz-add.component.html
- web/src/app/admin/clazz/clazz-edit/clazz-edit.component.html
- web/src/app/app.component.ts
- web/src/app/index/index.component.ts
- web/src/app/login/login.component.ts
- web/src/app/service/clazz.service.ts
- web/src/app/service/user.service.ts
- web/src/app/validator/common-validator.ts
> 登陆与注销，向浏览器中缓存登陆状态

- api/src/main/java/com/example/api/controller/UserController.java
- api/src/main/java/com/example/api/service/UserService.java
- api/src/main/java/com/example/api/service/UserServiceImpl.java
- api/src/test/java/com/example/api/controller/KlassControllerTest.java
- api/src/test/java/com/example/api/repository/KlassRepositoryTest.java
- web/src/app/admin/personal/personal-edit/personal-edit.component.ts
- web/src/app/admin/personal/personal-index/personal-index.component.ts
- web/src/app/index/index.component.ts
- web/src/app/service/user.service.ts
> admin->personal->index

- api/src/main/java/com/example/api/service/TeacherServiceImpl.java
- web/src/app/admin/site/site-index/site-index.component.html
- web/src/app/admin/site/update-teacher-index-password/update-teacher-index-password.component.html
- web/src/app/admin/site/update-teacher-index-password/update-teacher-index-password.component.ts
- web/src/app/admin/student/student-add/student-add.component.html
- web/src/app/admin/student/student-add/student-add.component.ts
- web/src/app/admin/teacher/teacher-add/teacher-add.component.html
- web/src/app/admin/teacher/teacher-add/teacher-add.component.ts
- web/src/app/service/teacher.service.ts
> 管理端-》系统设置-》修改默认密码

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/TermController.java
- api/src/main/java/com/example/api/repository/specs/TermSpecs.java
- api/src/main/java/com/example/api/service/TermServiceImpl.java
> admin->term->state decs

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/CourseController.java
- api/src/main/java/com/example/api/entity/Course.java
- api/src/main/java/com/example/api/entity/Term.java
- api/src/main/java/com/example/api/repository/CourseRepository.java
- api/src/main/java/com/example/api/repository/specs/CourseSpecs.java
- api/src/main/java/com/example/api/service/CourseService.java
- api/src/main/java/com/example/api/service/CourseServiceImpl.java
- web/src/app/service/course.service.ts
- web/src/app/service/student.service.ts
- web/src/app/service/term.service.ts
- web/src/app/teacher/course/course-add/course-add.component.ts
- web/src/app/teacher/course/course-index/course-index.component.ts
> 课程管理 => 增删改查

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/ClazzController.java
- api/src/main/java/com/example/api/repository/ScheduleRepository.java
- api/src/main/java/com/example/api/service/ClazzService.java
- api/src/main/java/com/example/api/service/ClazzServiceImpl.java
- api/src/main/java/com/example/api/service/ScheduleService.java
- api/src/main/java/com/example/api/service/ScheduleServiceImpl.java
- api/src/test/java/com/example/api/service/KlassServiceImplTest.java
- web/src/app/service/clazz.service.ts
- web/src/app/teacher/schedule/schedule-add/course-time/course-time.component.html
> 排课管理=》clazzesHaveSelectCourse方法数据请求

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/ScheduleController.java
- api/src/main/java/com/example/api/controller/TermController.java
- api/src/main/java/com/example/api/repository/ScheduleRepository.java
- api/src/main/java/com/example/api/repository/specs/ScheduleSpecs.java
- api/src/main/java/com/example/api/service/ScheduleService.java
- api/src/main/java/com/example/api/service/ScheduleServiceImpl.java
- web/src/app/admin/clazz/clazz-mebers-edit/clazz-mebers-edit.component.ts
- web/src/app/service/schedule.service.ts
- web/src/app/teacher/schedule/schedule-index/schedule-index.component.ts
- web/src/app/teacher/task/task-index/task-index.component.ts
> teacher->task->分页

- api/src/main/java/com/example/api/controller/StudentController.java
- api/src/main/java/com/example/api/repository/ScheduleRepository.java
- api/src/main/java/com/example/api/service/StudentService.java
- api/src/main/java/com/example/api/service/StudentServiceImpl.java
- api/src/test/java/com/example/api/service/StudentServiceImplTest.java
- web/src/app/service/clazz.service.ts
- web/src/app/service/student.service.ts
- web/src/app/teacher/task/task-index/task-index.component.ts
> teacher->task->查看学生->page、查询

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/ScheduleController.java
- api/src/main/java/com/example/api/controller/StudentController.java
- api/src/main/java/com/example/api/entity/Schedule.java
- api/src/main/java/com/example/api/entity/forType/forTaskStudentAdd/ForTaskStudentAdd.java
- api/src/main/java/com/example/api/repository/ClazzRepository.java
- api/src/main/java/com/example/api/repository/StudentRepository.java
- api/src/main/java/com/example/api/service/ScheduleService.java
- api/src/main/java/com/example/api/service/ScheduleServiceImpl.java
- api/src/main/java/com/example/api/service/StudentService.java
- api/src/main/java/com/example/api/service/StudentServiceImpl.java
- web/src/app/service/schedule.service.ts
- web/src/app/service/student.service.ts
- web/src/app/service/studentSchedule.service.ts
- web/src/app/teacher/task/task-index/task-index.component.ts
- web/src/app/teacher/task/view-student-add/view-student-add.component.html
- web/src/app/teacher/task/view-student-add/view-student-add.component.ts
- web/src/app/teacher/task/view-student/view-student.component.ts
> teacher->task->查看学生->新增

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/StudentController.java
- api/src/main/java/com/example/api/repository/StudentRepository.java
- api/src/main/java/com/example/api/service/StudentService.java
- api/src/main/java/com/example/api/service/StudentServiceImpl.java
- web/src/app/service/schedule.service.ts
- web/src/app/service/student.service.ts
- web/src/app/teacher/task/task-index/task-index.component.ts
- web/src/app/teacher/task/view-student/view-student.component.ts
> teacher->task->查看学生->=分页、查询

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/controller/ScheduleController.java
- api/src/main/java/com/example/api/controller/StudentController.java
- api/src/main/java/com/example/api/entity/Schedule.java
- api/src/main/java/com/example/api/entity/forType/forTaskStudentAdd/ForTaskStudentAdd.java
- api/src/main/java/com/example/api/repository/ClazzRepository.java
- api/src/main/java/com/example/api/repository/StudentRepository.java
- api/src/main/java/com/example/api/service/ScheduleService.java
- api/src/main/java/com/example/api/service/ScheduleServiceImpl.java
- api/src/main/java/com/example/api/service/StudentService.java
- api/src/main/java/com/example/api/service/StudentServiceImpl.java
- web/src/app/service/schedule.service.ts
- web/src/app/service/student.service.ts
- web/src/app/service/studentSchedule.service.ts
- web/src/app/teacher/task/task-index/task-index.component.ts
- web/src/app/teacher/task/view-student-add/view-student-add.component.html
- web/src/app/teacher/task/view-student-add/view-student-add.component.ts
- web/src/app/teacher/task/view-student/view-student.component.ts
> teacher->task->查看学生->移除、新增的index

- api/src/main/java/com/example/api/controller/DispatchController.java
- api/src/main/java/com/example/api/entity/forType/forCourseScheduleGetData/ForCourseScheduleGetData.java
- api/src/main/java/com/example/api/service/DispatchService.java
- api/src/main/java/com/example/api/service/DispatchServiceImpl.java
- web/src/app/service/courseSchedule.service.ts
- web/src/app/teacher/clazz-schedule/term-schedule/term-schedule.component.ts
- web/src/app/teacher/clazz-schedule/week-schedule/week-schedule.component.ts
> 教师端 =》课程表 =》 getData 

- web/src/app/service/studentSchedule.service.ts
- web/src/app/teacher/task/view-student-add/view-student-add.component.html
- web/src/app/teacher/task/view-student-add/view-student-add.component.ts
> teacher->task->viewStudent->add->学生选择组件只显示已选班级的学生

- api/src/main/java/com/example/api/controller/DispatchController.java
- api/src/main/java/com/example/api/controller/ScheduleController.java
- api/src/main/java/com/example/api/entity/forType/forScheduleAdd/DispatchForSchedule.java
- api/src/main/java/com/example/api/entity/forType/forScheduleAdd/ForScheduleAdd.java
- api/src/main/java/com/example/api/entity/forType/forScheduleEdit/ForScheduleEdit.java
- api/src/main/java/com/example/api/repository/ScheduleRepository.java
- api/src/main/java/com/example/api/service/DispatchService.java
- api/src/main/java/com/example/api/service/DispatchServiceImpl.java
- api/src/main/java/com/example/api/service/RoomService.java
- api/src/main/java/com/example/api/service/RoomServiceImpl.java
- api/src/main/java/com/example/api/service/ScheduleService.java
- api/src/main/java/com/example/api/service/ScheduleServiceImpl.java
- ngAndTp5/api/application/api/controller/ScheduleController.php
- web/src/app/service/dispatch.service.ts
- web/src/app/service/schedule.service.ts
- web/src/app/teacher/schedule/schedule-edit/schedule-edit.component.ts
- web/src/app/teacher/schedule/schedule-edit/time-add/course-time2/course-time2.component.ts
- web/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.ts
> scheduleEdit请求数据

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/service/UserServiceImpl.java
- web/src/app/admin/personal/personal-edit/personal-edit.component.html
- web/src/app/teacher/schedule/schedule-add/course-time/course-time.component.html
- web/src/app/teacher/schedule/schedule-add/course-time/course-time.component.ts
- web/src/app/teacher/schedule/schedule-add/schedule-add.component.ts
> 修复更换班级后的小单元显示bug

- api/src/main/java/com/example/api/controller/UserController.java
- api/src/main/java/com/example/api/service/UserService.java
- api/src/main/java/com/example/api/service/UserServiceImpl.java
- web/src/app/admin/personal/personal-edit/personal-edit.component.html
- web/src/app/admin/personal/personal-edit/personal-edit.component.ts
- web/src/app/service/user.service.ts
- web/src/app/validator/validator/validator-class.directive.ts
> 个人中心组件debug

- api/src/main/java/com/example/api/config/CommandLineRunnerImpl.java
- api/src/main/java/com/example/api/service/StudentServiceImpl.java
- api/src/main/java/com/example/api/service/UserServiceImpl.java
- web/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.html
- web/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.ts
- web/src/app/admin/student/student-add/student-add.component.ts
- web/src/app/admin/teacher/teacher-add/teacher-add.component.html
- web/src/app/admin/teacher/teacher-add/teacher-add.component.ts
> 删除班级成员，班级人数减少;

- web/src/app/admin/clazz/clazz-add/clazz-add.component.html
- web/src/app/admin/clazz/clazz-edit/clazz-edit.component.html
- web/src/app/admin/clazz/clazz-mebers-edit/clazz-members-edit.component.html
- web/src/app/admin/clazz/clazz-members-add/clazz-members-add.component.html
- web/src/app/admin/clazz/clazz-members/clazz-members.component.html
- web/src/app/admin/personal/personal-edit/personal-edit.component.html
- web/src/app/admin/room/room-add/room-add.component.html
- web/src/app/admin/room/room-edit/room-edit.component.html
- web/src/app/admin/site/update-teacher-index-password/update-teacher-index-password.component.html
- web/src/app/admin/student/student-add/student-add.component.html
- web/src/app/admin/student/student-edit/student-edit.component.html
- web/src/app/admin/student/student-update-password/student-update-password.component.html
- web/src/app/admin/teacher/teacher-add/teacher-add.component.html
- web/src/app/admin/teacher/teacher-edit/teacher-edit.component.html
- web/src/app/admin/teacher/teacher-update-password/teacher-update-password.component.html
- web/src/app/admin/term/add/term-add.component.html
- web/src/app/admin/term/edit/term-edit.component.html
- web/src/app/teacher/clazz-schedule/term-schedule/term-schedule.component.html
- web/src/app/teacher/course/course-add/course-add.component.html
- web/src/app/teacher/course/course-edit/course-edit.component.html
- web/src/app/teacher/schedule/schedule-add/schedule-add.component.html
- web/src/app/teacher/schedule/schedule-edit/clazz-add/clazz-add.component.html
- web/src/app/teacher/schedule/schedule-edit/name-edit/name-edit.component.html
- web/src/app/teacher/schedule/schedule-edit/program-add/program-add.component.html
- web/src/app/teacher/schedule/schedule-edit/program-edit/program-edit.component.html
- web/src/app/teacher/schedule/schedule-edit/schedule-edit.component.html
- web/src/app/teacher/schedule/schedule-edit/time-add/time-add.component.html
- web/src/app/teacher/task/view-student-add/view-student-add.component.html
- web/src/app/teacher/task/view-student-fraction/view-student-fraction.component.html
- web/src/app/teacher/task/view-student/view-student.component.html
> 面包屑导航的a标签的url
